### ISSUE TITLE
Uncaught Error: Call to a member function isLowerThan() on int

### ISSUE THREAD

**Issue by amin212121** [FriendsOfShopware/shopware-sentry-bundle#14]
### Actual behaviour

After updating plugin to 0.2.0 I have this problem

![Image](https://github.com/user-attachments/assets/87b2dfd0-1ef5-4703-af29-25640277a7b7)

### Expected behaviour

-

### Steps to Reproduce?

-

**Comment by amin212121** [comment]
@amenk

**Comment by amenk** [comment]
Can you debug which is the thrown exception?
Feel free to make a PR, will take me some days to look into it. But it should be easy to fix

**Comment by shyim** [comment]
I think because monolog major versions, they switched at some point to enum

**Comment by amenk** [comment]
@shyim Probably we should use some method_exists / instanceOf magic to support multiple versions of Monolog?
@amin212121 what versions are you using? What is `composer show` printing?

**Comment by sjerdo** [comment]
Its because of the change in signature of LogWare::getLogLevel between SW 6.5 and 6.6, and this package still supporting 6.5 according to composer.json

I've created a patch in #17
