### ISSUE TITLE
Issue #8 is breaking compatibility to shopware 6.5

### ISSUE THREAD

**Issue by ischmittis** [FriendsOfShopware/shopware-sentry-bundle#15]
### PHP Version

8.2

### Shopware Version

6.5

### Plugin Version

0.2.0

### Actual behaviour

The changes for Issue #8 is breaking the compatibility for shopware 6.5. 

`request.CRITICAL: Uncaught PHP Exception Error: "Call to a member function isLowerThan() on int" at FlowLogSubscriber.php line 36 {"exception":"[object] (Error(code: 0): Call to a member function isLowerThan() on int at /server/data/www/apache2.2/segger-shopware/releases/64/vendor/frosh/sentry-bundle/src/Subscriber/FlowLogSubscriber.php:36)"} []`

In shopware 6.5 the return type of $logLevel is int(), so the method isLowerThan is not available.

### Expected behaviour

Set compatibility version for 0.2.0 to shopware 6.6

### Steps to Reproduce?

Use a shopware 6.5 installation and configure sentry.

**Comment by sjerdo** [comment]
This won't help since version 0.2.0 is already tagged. There should be a new version 0.2.1 which supports both 6.5 and 6.6 by fixing the issue
