### ISSUE TITLE
Support business events / admin panel log events

### ISSUE THREAD

**Issue by amenk** [FriendsOfShopware/shopware-sentry-bundle#8]
## Capturing of event log warnings

For example when email templates don't compile, a event is logged in the admin panel (Admin Path: /admin#/sw/settings/logging/list), but no exception is thrown.

Is this case also supported by the plug-in?

### Test case

* Create and assign a contact form email template with the code `{{brokenTwig}}`
* Send the contact form

#### Excepted

And sentry error is triggerd

#### Currently

Only a business event warning is logged

![Event log](https://github.com/user-attachments/assets/158cc37a-791d-44fa-ae42-7b2521ddab5b)

**Comment by shyim** [comment]
We can't catch the exception as Shopware catches it and throws a logger error. But forwarding monolog error, or critical stuff to Sentry could do the trick. 🤔

**Comment by amenk** [comment]
Yes, no clue how to implement it. I can look into it.

I updated the original issue here to illustrated it more.

One common usecase are broken mail templates.

**Comment by amenk** [comment]
Pull request is on the way ...

**Comment by amenk** [comment]
![demo](https://github.com/user-attachments/assets/24446c83-d06e-4cfe-92f8-448ace105542)
